import { PageMeta } from "../components/seo/PageMeta";
import { Card } from "../components/ui/Card";

const EFFECTIVE_DATE = "June 14, 2026";

export function PrivacyPage() {
  return (
    <main className="py-8">
      <PageMeta
        title="Privacy"
        description="How Cursor Help handles your data: local-first chat indexing, account metadata, Stripe billing, Google OAuth, and export storage."
        path="/privacy"
      />

      <h1 className="text-4xl font-bold" style={{ fontFamily: "var(--font-display)" }}>
        Privacy
      </h1>
      <p className="mt-2 text-sm text-ch-text-secondary">Effective {EFFECTIVE_DATE}</p>

      <Card className="ch-rich-text mt-8 space-y-4 text-sm">
        <p>
          Cursor Help is local-first. Your Cursor database is read from a path you provide on your
          own machine. We do not upload your raw Cursor database to our servers.
        </p>

        <h2 className="text-base font-semibold text-ch-text">What we store</h2>
        <p>
          When you create an account, we store account metadata such as your email, display name,
          team membership, workspace names, and billing tier. This lets you sign in, manage teams,
          and upgrade to Pro across devices.
        </p>
        <p>
          Export files generated by the API are written to storage associated with your account or
          team workspace. You can delete exports from the app. We retain account metadata as long as
          your account is active unless you request deletion.
        </p>

        <h2 className="text-base font-semibold text-ch-text">Authentication</h2>
        <p>
          You may sign in with email and password or Google OAuth. When you use Google sign-in, we
          receive your Google account email and basic profile information from Google to create or
          link your Cursor Help account. We do not receive your Google password.
        </p>

        <h2 className="text-base font-semibold text-ch-text">Billing</h2>
        <p>
          Pro subscriptions are processed by Stripe. We do not store full payment card numbers on our
          servers. Stripe handles payment details according to their privacy policy. We store Stripe
          customer and subscription identifiers to manage your plan.
        </p>

        <h2 className="text-base font-semibold text-ch-text">Local indexing</h2>
        <p>
          Composer metadata (names, message counts, timestamps) may be indexed when you link a
          database path. Indexing runs against your linked path — your full chat database is not
          copied to Cursor Help cloud infrastructure for browsing.
        </p>

        <h2 className="text-base font-semibold text-ch-text">Deletion</h2>
        <p>
          To delete your account and associated metadata, contact us at{" "}
          <a href="mailto:hello@cursorhelp.com">hello@cursorhelp.com</a> from the email on your
          account. Local exports and your Cursor database remain on your machine — remove them
          directly from your filesystem.
        </p>

        <h2 className="text-base font-semibold text-ch-text">Contact</h2>
        <p>
          Privacy questions:{" "}
          <a href="mailto:hello@cursorhelp.com">hello@cursorhelp.com</a>. See also our{" "}
          <a href="/contact">Contact</a> page.
        </p>

        <p>
          Cursor Help is not affiliated with, endorsed by, or sponsored by Cursor or Anysphere.
        </p>
      </Card>
    </main>
  );
}
